#!/usr/bin/env python3

# Super simple script that fills in a README

def main():
    # Simple data
    title = "My Awesome Workflow"
    description = "This is a test workflow"
    date = "2025-01-01"
    
    # Create README content
    readme_content = f"""# {title}

## Description
{description}

## Info
- Generated on: {date}
- Status: ✅ Working
- Version: 1.0

## Details
This README was generated by a simple Python script!
"""
    
    # Write to file
    with open('docs/README-test.md', 'w') as f:
        f.write(readme_content)
    
    print("✅ README created: docs/README-test.md")
    print(f"   Title: {title}")
    print(f"   Size: {len(readme_content)} characters")

if __name__ == '__main__':
    main()
