#!/usr/bin/env python3
import argparse
import sys
from datetime import datetime


def main():
    parser = argparse.ArgumentParser(description="Generate a simple README from template or default content")
    parser.add_argument("--output", required=True, help="Where to save the README")
    parser.add_argument("--title", default="My Workflow", help="Title of the README")
    parser.add_argument("--description", help="Description text")
    parser.add_argument("--version", help="Version string")
    parser.add_argument("--template", help="Optional template file to load")
    args = parser.parse_args()

    # Data used for placeholder replacement
    data = {
        "{{TITLE}}": args.title,
        "{{DESCRIPTION}}": "This is a test workflow",
        "{{DATE}}": datetime.utcnow().strftime("%Y-%m-%d"),
        "{{VERSION}}": args.version or "1.0",
    }

    # If template provided, load it
    if args.template:
        try:
            with open(args.template, "r", encoding="utf-8") as f:
                readme_content = f.read()
        except FileNotFoundError:
            print(f"❌ Template not found: {args.template}")
            sys.exit(1)

        # Replace all placeholders
        for placeholder, value in data.items():
            readme_content = readme_content.replace(placeholder, value)

    else:
        # Default fallback content
         readme_content = f"""# {data['{{TITLE}}']}

## Description
{data["{{DESCRIPTION}}"]}

## Info
- Generated on: {data["{{DATE}}"]}
- Status: ✅ Working
- Version: {data["{{VERSION}}"]}

## Details
This README was generated by a simple Python script!
"""

    # Write final README
    with open(args.output, "w", encoding="utf-8") as f:
        f.write(readme_content)

    print(f"✅ README created: {args.output}")
    print(f"   Title: {data['{{TITLE}}']}")
    print(f"   Description: {data['{{DESCRIPTION}}']}")
    print(f"   Date: {data['{{DATE}}']}")
    print(f"   Version: {data['{{VERSION}}']}")
    print(f"   Size: {len(readme_content)} characters")

if __name__ == "__main__":
    main()
