#!/usr/bin/env python3
import argparse

# Step 2: Accept command-line arguments

def main():
    # Parse arguments
    parser = argparse.ArgumentParser(description='Generate a simple README')
    parser.add_argument('--output', required=True, help='Where to save the README')
    parser.add_argument('--title', default='My Workflow', help='Title of the README')
    args = parser.parse_args()
    
    # Simple data
    title = args.title
    description = "This is a test workflow"
    date = "2025-01-01"
    
    # Create README content
    readme_content = f"""# {title}

## Description
{description}

## Info
- Generated on: {date}
- Status: ✅ Working
- Version: 1.0

## Details
This README was generated by a simple Python script!
"""
    
    # Write to file
    with open(args.output, 'w') as f:
        f.write(readme_content)
    
    print(f"✅ README created: {args.output}")
    print(f"   Title: {title}")
    print(f"   Size: {len(readme_content)} characters")

if __name__ == '__main__':
    main()
