name: Branch naming

#on:
 # create:

on:
  push:
    branches-ignore:
      - main
      - develop
  create:
    branches-ignore:
      - main
      - develop

#on:
#  push:
#    branches-ignore:
 #     - main
  #    - develop
 # pull_request:

jobs:
  branch-naming-rules:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Ensure branch is based on any remote branch
        run: |
          BRANCH_NAME="${GITHUB_REF#refs/heads/}"
          git fetch --all
          VALID_BASE=false
          for REMOTE_BRANCH in $(git branch -r | sed 's/origin\///'); do
            BASE=$(git merge-base HEAD "origin/$REMOTE_BRANCH" || true)
            if [ "$BASE" = "$(git rev-parse origin/$REMOTE_BRANCH)" ]; then
              VALID_BASE=true
              break
            fi
          done

          if [ "$VALID_BASE" = false ]; then
            echo "❌ Branch '$BRANCH_NAME' is not based on any remote branch."
            exit 1
          fi


      - name: Validate branch name on create
        if: github.event_name == 'create'
        run: |
          BRANCH_NAME="${GITHUB_REF#refs/heads/}"
          echo "Checking branch name: $BRANCH_NAME"
          if [[ ! "$BRANCH_NAME" =~ ^(hot-fix-)?[A-Z]{3}-[a-zA-Z0-9]+-ERP-[0-9]{5}$ ]]; then
            echo "❌ Invalid branch name: $BRANCH_NAME"
            exit 1
          fi

      - name: Validate branch name on push
        if: github.event_name == 'push'
        uses: deepakputhraya/action-branch-name@master
        with:
          regex: '^(hot-fix-)?[A-Z]{3}-[a-zA-Z0-9]+-ERP-[0-9]{5}$'
          min_length: 10
          max_length: 100

      - name: Comment on PR if branch name is invalid
        if: failure() && github.event_name == 'pull_request'
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          message: |
            ⚠️ **Branch name does not follow the convention!**
            Please rename your branch to match one of the following formats:
            - `hot-fix/ABC-login-ERP-12345`
            - `ABC-login-ERP-12345`

