name: Branch naming

on:
  push:
    branches-ignore:
      - main
      - develop
  create:
    branches-ignore:
      - main
      - develop

jobs:
  branch-naming-rules:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Validate branch name on create
        if: github.event_name == 'create'
        run: |
          BRANCH_NAME="${GITHUB_REF#refs/heads/}"
          echo "Checking branch name: $BRANCH_NAME"
          if [[ ! "$BRANCH_NAME" =~ ^(hot-fix-)?[A-Z]{3}-[a-zA-Z0-9]+-ERP-[0-9]{5}$ ]]; then
            echo "❌ Invalid branch name: $BRANCH_NAME"
            exit 1
          fi

      - name: Validate branch name on push
        if: github.event_name == 'push'
        uses: deepakputhraya/action-branch-name@master
        with:
          #regex: '^(hot-fix-)?[A-Z]{3}-[a-zA-Z0-9]+-ERP-[0-9]{5}$'
         # regex: '^(hot-fix-)?[A-Z0-9]{2,}-[a-zA-Z0-9]+-ERP-[0-9]{1,5}$'
         # regex: '^(hot-fix-)?[A-Z0-9]+-[a-zA-Z0-9]+-ERP-[0-9]+$'
          regex: '.*'
          min_length: 10
          max_length: 100

      - name: Debug Jira API call
        run: |
          BRANCH_NAME="${GITHUB_REF#refs/heads/}"
          TICKET=$(echo "$BRANCH_NAME" | grep -oE '[A-Z0-9]+-[0-9]+')
          echo "Checking Jira ticket: $TICKET"

          curl -u "${{ secrets.JIRA_USER }}:${{ secrets.JIRA_API_TOKEN }}" \
            -X GET \
            -H "Accept: application/json" \
            "${{ secrets.JIRA_BASE_URL }}/rest/api/3/issue/$TICKET" -v
        env:
          JIRA_USER: ${{ secrets.JIRA_USER }}
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
          JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}

      - name: Extract Jira Ticket Key
        id: extract
        run: |
          BRANCH_NAME="${GITHUB_REF#refs/heads/}"
          echo "Branch: $BRANCH_NAME"
          TICKET=$(echo "$BRANCH_NAME" | grep -oE '[A-Z0-9]+-[0-9]+')
          echo "Extracted ticket: $TICKET"
          echo "ticket=$TICKET" >> $GITHUB_OUTPUT

      - name: Validate Jira Ticket Exists
        run: |
          echo "Checking Jira ticket: ${{ steps.extract.outputs.ticket }}"
          RESPONSE=$(curl -s -o /dev/null -w "%{http_code}" \
            -u "${{ secrets.JIRA_USER }}:${{ secrets.JIRA_API_TOKEN }}" \
            -X GET \
            -H "Accept: application/json" \
            "${{ secrets.JIRA_BASE_URL }}/rest/api/3/issue/${{ steps.extract.outputs.ticket }}")

          if [ "$RESPONSE" -ne 200 ]; then
            echo "❌ Jira ticket not found: ${{ steps.extract.outputs.ticket }}"
            exit 1
          else
            echo "✅ Jira ticket exists: ${{ steps.extract.outputs.ticket }}"
          fi
        env:
          JIRA_USER: ${{ secrets.JIRA_USER }}
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
          JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}

      - name: Comment on PR if branch name is invalid
        if: failure() && github.event_name == 'pull_request'
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          message: |
            ⚠️ **Branch name does not follow the convention!**
            Please rename your branch to match one of the following formats:
            - `hot-fix/ABC-login-ERP-12345`
            - `ABC-login-ERP-12345`
