name: Branch naming

#on:
 # create:
on:
  push:
    branches: ["**"]
  create:
    branches: ["**"] 

#on:
#  push:
#    branches-ignore:
 #     - main
  #    - develop
 # pull_request:

jobs:
  branch-naming-rules:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Ensure branch is based on main
        run: |
          git fetch origin main
          BASE=$(git merge-base HEAD origin/main)
          if [ "$BASE" != "$(git rev-parse origin/main)" ]; then
            echo "❌ Branch is not based on main"
            exit 1
          fi

      - name: Validate branch name
        uses: deepakputhraya/action-branch-name@master
        with:
          regex: '^(hot-fix-)?[A-Z]{3}-[a-zA-Z0-9]+-ERP-\d{5}$'
          min_length: 10
          max_length: 100


       
      - name: Comment on PR if branch name is invalid
        if: failure() && github.event_name == 'pull_request'
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          message: |
            ⚠️ **Branch name does not follow the convention!**
            Please rename your branch to match:
            - `feature/<name>`
            - `bugfix/<name>`
            - `hotfix/<name>`
            - `release/<name>`
            - `docs/<name>`
