name: Branch naming

#on:
 # create:
on:
  push:
    branches: ["**"]
  create:
    branches: ["**"] 

#on:
#  push:
#    branches-ignore:
 #     - main
  #    - develop
 # pull_request:

jobs:
  branch-naming-rules:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Ensure branch is based on any remote branch
        run: |
          BRANCH_NAME="${GITHUB_REF#refs/heads/}"
          git fetch --all
          VALID_BASE=false
          for REMOTE_BRANCH in $(git branch -r | sed 's/origin\///'); do
            BASE=$(git merge-base HEAD "origin/$REMOTE_BRANCH" || true)
            if [ "$BASE" = "$(git rev-parse origin/$REMOTE_BRANCH)" ]; then
              VALID_BASE=true
              break
            fi
          done

          if [ "$VALID_BASE" = false ]; then
            echo "❌ Branch '$BRANCH_NAME' is not based on any remote branch."
            exit 1
          fi


      - name: Validate branch name
        uses: deepakputhraya/action-branch-name@master
        with:
          regex: '^(hot-fix-)?[A-Z]{3}-[a-zA-Z0-9]+-ERP-\d{5}$'
          min_length: 10
          max_length: 100


       
      - name: Comment on PR if branch name is invalid
        if: failure() && github.event_name == 'pull_request'
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          message: |
            ⚠️ **Branch name does not follow the convention!**
            Please rename your branch to match:
            - `feature/<name>`
            - `bugfix/<name>`
            - `hotfix/<name>`
            - `release/<name>`
            - `docs/<name>`
