name: Detect File Change

on:
  workflow_call:
    inputs:
      watched_path:
        description: "Path to check for changes"
        required: true
        type: string
    outputs:
      found:
        description: "Whether the watched path changed"
        value: ${{ jobs.detect.outputs.found }}
      files:
        description: "List of changed files"
        value: ${{ jobs.detect.outputs.files }}

jobs:
  detect:
    runs-on: ubuntu-latest
    outputs:
      found: ${{ steps.result.outputs.found }}
      files: ${{ steps.result.outputs.files }}

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Detect changed files
        id: result
        run: |
          set -e
          AFTER="${{ github.event.release.tag_name }}"
          WATCHED_PATH="${{ inputs.watched_path }}"

          git fetch --tags --quiet
          PREV_TAG=$(git tag --sort=-creatordate | grep -A1 "$AFTER" | tail -n1 || true)

          if [ -z "$PREV_TAG" ] || [ "$PREV_TAG" = "$AFTER" ]; then
            CHANGED=$(git ls-tree -r --name-only "$AFTER")
          else
            CHANGED=$(git diff --name-only "$PREV_TAG" "$AFTER")
          fi

          if [ -z "$CHANGED" ]; then
            echo "found=false" >> $GITHUB_OUTPUT
            exit 0
          fi

          if echo "$CHANGED" | grep -q "$WATCHED_PATH"; then
            echo "found=true" >> $GITHUB_OUTPUT
          else
            echo "found=false" >> $GITHUB_OUTPUT
            exit 0
          fi

          echo "files<<EOF" >> $GITHUB_OUTPUT
          echo "$CHANGED" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
