name: Create Jira Task on Release

on:
 # release:
  #  types: [published]

  workflow_dispatch:

jobs:
  create-jira-task:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create Jira task
        uses: atlassian/gajira-create@v3
        env:
          JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
          JIRA_USER_EMAIL: ${{ secrets.JIRA_USER }}
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
        with:
          project: DEMO
          issuetype: Task
          summary: "Prepare new installer for App.java changes"
          description: |
            App.java was modified in the latest release.
            Please review and rebuild the installer if necessary.
          assignee: "mihaela.nikolovska@students.finki.ukim.mk"
