name: Notify on App.java Changes

on:
  release:
    types: [published]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  find_previous_tag:
    runs-on: ubuntu-latest
    outputs:
      previous_tag: ${{ steps.prev.outputs.tag }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Find previous tag
        id: prev
        run: |
          current_tag="${{ github.event.release.tag_name }}"
          previous_tag=$(git describe --tags --abbrev=0 "${current_tag}^" 2>/dev/null || echo "")
          echo "Previous tag: $previous_tag"
          echo "tag=$previous_tag" >> $GITHUB_OUTPUT

  check_file_changes:
    needs: find_previous_tag
    uses: m-nikolovska-mak-system/reusable-actions-library/.github/workflows/check-for-file-changes.yml@main
    with:
      watched_files: 'oneProjectWed/src/java/com/miha/app/App.java'
      base_ref: ${{ needs.find_previous_tag.outputs.previous_tag }}
      head_ref: ${{ github.event.release.tag_name }}

  send_teams_notification:
    needs: check_file_changes
    if: needs.check_file_changes.outputs.files_changed == 'true'
    uses: m-nikolovska-mak-system/reusable-actions-library/.github/workflows/send-teams-notification.yml@main
    with:
      title: '🚀 App.java Changed in Release'
      message: |
        ⚠️ **Action Required:** Prepare new installer for Template Designer  
        Changed files: ${{ needs.check_file_changes.outputs.changed_files_list }}
      color: 'Warning'
      changed_files: ${{ needs.check_file_changes.outputs.changed_files_list }}
      link_url: ${{ github.event.release.html_url }}
      link_text: 'View Release'
    secrets:
      teams_webhook_url: ${{ secrets.TEAMS_WEBHOOK_INSTALLER_URL }}
