name: Notify on Release

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  detect:
    runs-on: ubuntu-latest
    outputs:
      found: ${{ steps.detect.outputs.found }}
      files: ${{ steps.detect.outputs.files }}
    steps:
      - id: detect
        uses: ./.github/actions/detect-file-change
        with:
          watched_path: "oneProjectWed/src/java/com/miha/app/App.java"

  notify:
    needs: detect
    if: needs.detect.outputs.found == 'true'
    uses: ./.github/workflows/reusable-teams-notifier.yml
    with:
      notification_title: "🚀 Files Updated in New Release"
      action_required_message: "⚠️ Prepare new installer for Template Designer"
      card_color: "Accent"
      files: ${{ needs.detect.outputs.files }}
    secrets:
      teams_webhook_url: ${{ secrets.TEAMS_WEBHOOK_INSTALLER_URL }}
