name: Notify on Release

on:
  release:
    types: [published, edited, created]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  notify:
    uses: ./.github/workflows/teams-notif-on-update.yml
    with:
      notification_title: 'ЁЯЪА New Release Published'
      action_required_message: 'тЪая╕П **Action Required:** Prepare new installer for Template Designer'
      card_color: 'Accent'
      show_files: true
      watched_path: 'oneProjectWed/src/java/com/miha/app/App.java' 
    secrets:
      teams_webhook_url: ${{ secrets.TEAMS_WEBHOOK_INSTALLER_URL }}
