name: Notify on App.java Changes

on:
  release:
    types: [published]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  find_previous_tag:
    runs-on: ubuntu-latest
    outputs:
      base_ref: ${{ steps.set.outputs.base_ref }}
      head_ref: ${{ steps.set.outputs.head_ref }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Determine base and head refs
        id: set
        run: |
          # Make sure we have all tags
          git fetch --tags

          current_tag="${{ github.event.release.tag_name }}"
          echo "Current tag: $current_tag"

          # Try to find previous tag
          previous_tag=$(git describe --tags --abbrev=0 "${current_tag}^" 2>/dev/null || echo "")

          # Fallback: if no previous tag found, use last commit
          if [ -z "$previous_tag" ]; then
            echo "⚠️ No previous tag found, using HEAD~1 as base."
            previous_tag="HEAD~1"
          fi

          echo "Base ref (previous tag): $previous_tag"
          echo "Head ref (current tag): $current_tag"

          echo "base_ref=$previous_tag" >> $GITHUB_OUTPUT
          echo "head_ref=$current_tag" >> $GITHUB_OUTPUT

  check_file_changes:
      uses: m-nikolovska-mak-system/reusable-actions-library/.github/workflows/check-for-file-changes.yml@main
      with:
        watched_files: 'oneProjectWed/src/java/com/miha/app/App.java'

  send_teams_notification:
    needs: check_file_changes
    if: needs.check_file_changes.outputs.files_changed == 'true'
    uses: m-nikolovska-mak-system/reusable-actions-library/.github/workflows/send-teams-notification.yml@main
    with:
      title: '🚀 App.java Changed in Release'
      message: |
        ⚠️ **Action Required:** Prepare new installer for Template Designer  
        Changed files: ${{ needs.check_file_changes.outputs.changed_files_list }}
      color: 'Warning'
      changed_files: ${{ needs.check_file_changes.outputs.changed_files_list }}
      link_url: ${{ github.event.release.html_url }}
      link_text: 'View Release'
    secrets:
      teams_webhook_url: ${{ secrets.TEAMS_WEBHOOK_INSTALLER_URL }}
