name: Notify on Release
on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  check_app_change:
    runs-on: ubuntu-latest
    outputs:
      should_notify: ${{ steps.check.outputs.should_notify }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get current and previous tags
        id: tags
        run: |
          current_tag="${{ github.event.release.tag_name }}"
          prev_tag=$(git tag --sort=-creatordate | grep -B1 "$current_tag" | head -n1 || true)
          echo "current_tag=$current_tag" >> $GITHUB_OUTPUT
          echo "prev_tag=$prev_tag" >> $GITHUB_OUTPUT

      - name: Check if App.java changed
        id: check
        run: |
          if git diff --name-only ${{ steps.tags.outputs.prev_tag }} ${{ steps.tags.outputs.current_tag }} | grep -q 'oneProjectWed/src/java/com/miha/app/App.java'; then
            echo "should_notify=true" >> $GITHUB_OUTPUT
          else
            echo "should_notify=false" >> $GITHUB_OUTPUT
          fi

  notify:
    needs: check_app_change
    if: needs.check_app_change.outputs.should_notify == 'true'
    uses: ./.github/workflows/teams-notif-template.yml
    with:
      notification_title: "ЁЯЪА New Release Published"
      action_required_message: "тЪая╕П Prepare new installer for Template Designer"
      files: "oneProjectWed/src/java/com/miha/app/App.java"
    secrets:
      teams_webhook_url: ${{ secrets.TEAMS_WEBHOOK_INSTALLER_URL }}
