name: Notify on Release

on:
  release:
    types: [published]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  check_changes:
    runs-on: ubuntu-latest
    outputs:
      found: ${{ steps.detect.outputs.found }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Detect file changes
        id: detect
        run: |
          echo "🔍 Checking for file changes..."
          BEFORE=$(git rev-parse HEAD^ || echo "")
          AFTER=$(git rev-parse HEAD)
          WATCHED_PATH="oneProjectWed/src/java/com/miha/app/App.java"

          if [ -z "$BEFORE" ]; then
            echo "⚙️ Initial commit, listing all files..."
            CHANGED=$(git ls-tree -r --name-only "$AFTER")
          else
            CHANGED=$(git diff --name-only "$BEFORE" "$AFTER")
          fi

          echo "Changed files:"
          echo "$CHANGED"

          if echo "$CHANGED" | grep -q "$WATCHED_PATH"; then
            echo "✅ File changed: $WATCHED_PATH"
            echo "found=true" >> $GITHUB_OUTPUT
          else
            echo "ℹ️ Watched path not changed — skipping notification."
            echo "found=false" >> $GITHUB_OUTPUT
          fi

  notify:
    needs: check_changes
    if: needs.check_changes.outputs.found == 'true'
    uses: ./.github/workflows/teams-notify-template.yml
    with:
      notification_title: "🚀 New Release Published"
      action_required_message: "⚠️ Prepare new installer for Template Designer"
      card_color: "Accent"
    secrets:
      teams_webhook_url: ${{ secrets.TEAMS_WEBHOOK_INSTALLER_URL }}
