name: Notify on App.java Changes

on:
  release:
   types: [published]
  workflow_dispatch:

permissions:
  contents: read
  
jobs:
  check_file_changes:
    uses: m-nikolovska-mak-system/reusable-actions-library/.github/workflows/check-for-file-changes.yml@main
    with:
      watched_files: 'oneProjectWed/src/java/com/miha/app/App.java'
      
     
  debug_outputs:
    needs: check_file_changes
    runs-on: ubuntu-latest
    steps:
      - name: Print outputs from check_file_changes
        run: |
          echo "Files changed: ${{ needs.check_file_changes.outputs.files_changed }}"
          echo "Changed files list: ${{ needs.check_file_changes.outputs.changed_files_list }}"


  send_teams_notification:
    needs: check_file_changes
    if: needs.check_file_changes.outputs.files_changed == 'true'
    uses: m-nikolovska-mak-system/reusable-actions-library/.github/workflows/send-teams-notification.yml@main
    with:
      title: '🚀 App.java Changed in Release'
      message: |
           '⚠️ **Action Required:** Prepare new installer for Template Designer'
      release_version: ${{ github.event.release.tag_name || inputs.release_tag }}
      color: 'Warning'
      released_by: ${{ github.actor }}
      changed_files: ${{ needs.check_file_changes.outputs.changed_files_list }}
      link_url: ${{ 
        github.event.release.html_url || 
        (inputs.release_tag && format('https://github.com/{0}/releases/tag/{1}', github.repository, inputs.release_tag)) || 
        format('https://github.com/{0}/releases', github.repository)
       }}
      link_text: ${{ 
        github.event.release.html_url && 'View Release' || 
        inputs.release_tag && 'View Release' || 
        'View All Releases'
       }}
    secrets:
      teams_webhook_url: ${{ secrets.TEAMS_WEBHOOK_INSTALLER_URL }}
