name: Notify on App Changes

on:
#  release:
 #   types: [published]
 workflow_dispatch:

jobs:
  notify:
    uses: m-nikolovska-mak-system/reusable-actions-library/.github/workflows/release-file-watcher.yml@main
    with:
      watched_file: 'oneProjectWed/src/java/com/miha/app/App.java'
      notification_title: 'ЁЯЪА App.java Changed!'
      notification_message: 'тЪая╕П Prepare new installer for Template Designer'
    secrets:
     teams_webhook_url: ${{ secrets.TEAMS_WEBHOOK_INSTALLER_URL }}
