name: Reusable Teams Notifier
on:
  workflow_call:
    inputs:
      notification_title:
        description: 'Title for the Teams card'
        required: false
        type: string
        default: '🚀 Files Updated'
      action_required_message:
        description: 'Custom action message'
        required: false
        type: string
        default: '⚠️ **Action Required:** Please review changes'
      card_color:
        description: 'Accent color theme (Accent, Good, Warning, Attention)'
        required: false
        type: string
        default: 'Accent'
      files:
        description: 'List of changed files'
        required: false
        type: string
    secrets:
      teams_webhook_url:
        required: true

jobs:
  notify-teams:
    runs-on: ubuntu-latest
    steps:
      - name: Send Microsoft Teams notification
        env:
          TEAMS_WEBHOOK_URL: ${{ secrets.teams_webhook_url }}
          NOTIFICATION_TITLE: ${{ inputs.notification_title }}
          ACTION_MESSAGE: ${{ inputs.action_required_message }}
          CARD_COLOR: ${{ inputs.card_color }}
          FILES: ${{ inputs.files }}
        run: |
          set -e
      
          if [ -z "$TEAMS_WEBHOOK_URL" ]; then
            echo "❌ Missing teams_webhook_url secret."
            exit 1
          fi
      
          ACTOR="${{ github.actor }}"
          REPO="${{ github.repository }}"
          SHA="${{ github.sha }}"
          SHORT_SHA="${SHA:0:7}"
          TIMESTAMP=$(TZ='Europe/Belgrade' date +"%Y-%m-%d %H:%M %Z")
      
          PAYLOAD=$(cat <<'EOF'
          {
            "type": "message",
            "attachments": [
              {
                "contentType": "application/vnd.microsoft.card.adaptive",
                "content": {
                  "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
                  "type": "AdaptiveCard",
                  "version": "1.4",
                  "body": [
                    {
                      "type": "TextBlock",
                      "text": "$NOTIFICATION_TITLE",
                      "weight": "Bolder",
                      "size": "Large",
                      "color": "$CARD_COLOR"
                    },
                    {
                      "type": "TextBlock",
                      "text": "$ACTION_MESSAGE",
                      "wrap": true
                    },
                    {
                      "type": "TextBlock",
                      "text": "🔗 Commit: https://github.com/$REPO/commit/$SHA"
                    },
                    {
                      "type": "TextBlock",
                      "text": "🕒 Timestamp: $TIMESTAMP"
                    },
                    {
                      "type": "TextBlock",
                      "text": "📂 Files Changed:",
                      "weight": "Bolder"
                    },
                    {
                      "type": "TextBlock",
                      "text": "$FILES",
                      "fontType": "Monospace",
                      "wrap": true
                    }
                  ]
                }
              }
            ]
          }
          EOF
          )
      
          # Substitute variables in the payload
          PAYLOAD=$(echo "$PAYLOAD" | \
            sed "s|\$NOTIFICATION_TITLE|$NOTIFICATION_TITLE|g" | \
            sed "s|\$ACTION_MESSAGE|$ACTION_MESSAGE|g" | \
            sed "s|\$CARD_COLOR|$CARD_COLOR|g" | \
            sed "s|\$REPO|$REPO|g" | \
            sed "s|\$SHA|$SHA|g" | \
            sed "s|\$TIMESTAMP|$TIMESTAMP|g" | \
            sed "s|\$FILES|$FILES|g")
      
          echo "📤 Sending notification to Teams..."
          HTTP_CODE=$(curl -s -o /dev/null -w "%{http_code}" \
            -H "Content-Type: application/json" \
            -d "$PAYLOAD" "$TEAMS_WEBHOOK_URL")
      
          if [ "$HTTP_CODE" = "200" ] || [ "$HTTP_CODE" = "202" ]; then
            echo "✅ Teams notification sent successfully!"
          else
            echo "❌ Error: Teams webhook failed with status $HTTP_CODE"
            echo "$PAYLOAD"
            exit 1
          fi
