name: Notify on App Changes

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  notify:
    uses: m-nikolovska-mak-system/reusable-actions-library/.github/workflows/release-file-watcher.yml@main
    with:
      notification_title: 'ЁЯЪА App.java Changed!'
      action_required_message: 'тЪая╕П Prepare new installer for Template Designer'
      watched_file: 'oneProjectWed/src/java/com/miha/app/App.java'
    secrets:
      teams_webhook_url: ${{ secrets.TEAMS_WEBHOOK_INSTALLER_URL }}
