name: Notify on App Changes

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  check_and_notify:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get previous commit or tag
        id: prev
        run: |
          PREV=$(git rev-parse HEAD~1)
          echo "previous=$PREV" >> $GITHUB_OUTPUT

      - name: Check if App.java changed
        id: file_check
        run: |
          CHANGED=$(git diff --name-only ${{ steps.prev.outputs.previous }} HEAD | grep "oneProjectWed/src/java/com/miha/app/App.java" || true)
          if [ -n "$CHANGED" ]; then
            echo "✅ File changed"
            echo "changed=true" >> $GITHUB_OUTPUT
          else
            echo "ℹ️ File not changed"
            echo "changed=false" >> $GITHUB_OUTPUT
          fi

      - name: Notify via Teams
        if: steps.file_check.outputs.changed == 'true'
        uses: m-nikolovska-mak-system/reusable-actions-library/.github/workflows/send-teams-notification.yml@main 
        with:
          webhook_url: ${{ secrets.TEAMS_WEBHOOK_INSTALLER_URL }}
          title: '🚀 App.java Changed!'
          message: '⚠️ Prepare new installer for Template Designer'
          color: 'Good'
          files: 'oneProjectWed/src/java/com/miha/app/App.java'
      #  secrets:
       #   teams_webhook_url: ${{ secrets.TEAMS_WEBHOOK_INSTALLER_URL }}
