name: Notify on App.java Changes

on:
  release:
    types: [published]
  workflow_dispatch: 

permissions:
  contents: read

jobs:
  check-and-notify:
    uses: m-nikolovska-mak-system/reusable-actions-library/.github/workflows/release-file-watcher.yml@main
    with:
      watched_file: 'oneProjectWed/src/java/com/miha/app/App.java'
      notification_title: '🚀 App.java Changed in Release'
      notification_message: '⚠️ **Action Required:** Prepare new installer for Template Designer'
      card_color: 'Warning'
      show_changed_files: true
      link_url: https://github.com/${{ github.repository }}/commit/${{ github.sha }}
    secrets:
      teams_webhook_url: ${{ secrets.TEAMS_WEBHOOK_INSTALLER_URL }}
