name: Notify on App Changes

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  check_changes:
    uses: m-nikolovska-mak-system/reusable-actions-library/.github/workflows/check-for-file-changes.yml@main
    with:
      watched_file: 'oneProjectWed/src/java/com/miha/app/App.java'

  notify:
    needs: check_changes
    if: needs.check_changes.outputs.changed == 'true'
    uses: m-nikolovska-mak-system/reusable-actions-library/.github/workflows/send-teams-notification.yml@main
    with:
      notification_title: '🚀 App.java Changed!'
      notification_message: '⚠️ Prepare new installer for Template Designer'
      card_color: 'Good'
      files: ${{ needs.check_changes.outputs.changed_files }}
    secrets:
      teams_webhook_url: ${{ secrets.TEAMS_WEBHOOK_INSTALLER_URL }}
