name: Notify on App Changes

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Check for file changes
        id: diff
        uses: m-nikolovska-mak-system/reusable-actions-library/.github/actions/check-file-changes@main
        with:
          target_file: 'oneProjectWed/src/java/com/miha/app/App.java'

      - name: Notify via Teams
        if: steps.diff.outputs.changed == 'true'
        uses: m-nikolovska-mak-system/reusable-actions-library/.github/workflows/send-teams-notification.yml@main
        with:
          watched_file: 'oneProjectWed/src/java/com/miha/app/App.java'
          notification_title: '🚀 App.java Changed!'
          notification_message: '⚠️ Prepare new installer for Template Designer'
        secrets:
          teams_webhook_url: ${{ secrets.TEAMS_WEBHOOK_INSTALLER_URL }}
