name: Test File Change and Notify
on:
  workflow_dispatch:

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Check if file changed
        uses: m-nikolovska-mak-system/reusable-actions-library/.github/actions/check-file-changes@main
        id: file_check
        with:
          target_file: 'src/App.java'

      - name: Send Teams notification if file changed
        if: steps.file_check.outputs.changed == 'true'
        uses: m-nikolovska-mak-system/reusable-actions-library/.github/actions/send-teams-notification@main
        with:
          webhook_url: ${{ secrets.TEAMS_WEBHOOK_INSTALLER_URL }}
          message: "📢 File `src/App.java` has changed between releases!"
