name: Java Lint Check
description: 'Runs a basic syntax check on a Java file'
inputs:
  file:
    description: 'Path to the Java file'
    required: true
    default: 'src/java/com/miha/app/App.java'

runs:
  using: 'composite'
  steps:
    - name: Check Java file exists
      shell: bash
      run: |
        if [ ! -f "${{ inputs.file }}" ]; then
          echo "❌ File not found!"
          exit 1
        fi
        echo "✅ File exists"

    - name: Compile Java file
      shell: bash
      run: |
        javac "${{ inputs.file }}" || exit 1
        echo "✅ Java file compiled successfully"
